DROP TABLE IF EXISTS loan;
DROP TABLE IF EXISTS user_loan;
DROP TABLE IF EXISTS user_loan_extension;
DROP TABLE IF EXISTS users;

create table loan (
    base_rate numeric(38,2) not null,
    max_spread numeric(38,2) not null,
    limit_amount bigint not null,
    loan_id bigint generated by default as identity,
    bank_code varchar(255) not null,
    name varchar(255) not null,
    primary key (loan_id)
);
create table user_loan (
    interest_rate numeric(38,2) not null,
    maturity date not null,
    repayment_date integer not null,
    started_at date not null,
    loan_id bigint not null,
    total_amount bigint not null,
    total_repayment bigint not null,
    user_id bigint not null,
    user_loan_id bigint generated by default as identity,
    primary key (user_loan_id)
);
create table user_loan_extension (
    term_to_maturity integer not null,
    remaining_amount bigint not null,
    user_loan_extension_id bigint generated by default as identity,
    user_loan_id bigint not null unique,
    custom_name varchar(255),
    name varchar(255) not null,
    primary key (user_loan_extension_id)
);
create table users (
    birth_date date not null,
    user_id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (user_id)
);